name: CrateKeyShop 
main: fernanACM\KeyShop\KeyShop
version: 1.0.0
api: 5.3.0
author: NemesisFire2348
description: "Ein Store-Plugin zum Verkauf von Schlüsseln auf Ihrem Server. Nur für PocketMine-MP 5.0"
sofdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
  keyshop:
    permission: keyshop.acm
    description: "CrateKeyShop kauf dir Crate-Schlüssel"
    aliases: ["ks", "keys"]

permissions:
  keyshop.acm:
    default: true
