# ||| CrateKeyShop |||
# A store plugin to sell keys on your server. It accepts 
# all types of keys from each plugin, which is why it is unique in its kind.

# DO NOT TOUCH!
config-version: "1.0.0"
# Prefix plugin
Prefix: "_"
# Usa economyapi, bedrockeconomy, xp
Economy: 
  provider: bedrockeconomy
# Here put the command to give you a key
# {PLAYER} => Player name
# {KEY} => The key has to be received
# {AMOUNT} => The number of keys
Key-command: key {KEY} "{PLAYER}" {AMOUNT}
# EXAMPLE:
# KEYS:
# - {LINE} => Line break
# - {AMOUNT} => Number of keys
# - {PRICE} => Price of the key
# - "&" => Color
# KeyShop:
#   Common: // THE NAME OF THE KEY WILL GO HERE (MUST BE EXACT)
#     name: "&l&cCOMUN{LINE}&r&0x{AMOUNT} | cost: {PRICE}$" // OPTIONAL
#     price: 323 // Key price
#     image: "textures/items/cancel" // OPTIONAL - URL or PATH
#     amount: 2 // Number of keys to receive
KeyShop:
  Eisen:
    price: 350
    name: "&l&cCOMMON{LINE}&r&0x{AMOUNT} {LINE} | kostet: {PRICE}€"
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngegg.com%2Fen%2Fpng-ynkgz&psig=AOvVaw1qm2GlJ0j7nIvqVn4Oe7Mi&ust=1709039017441000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDzkc6IyYQDFQAAAAAdAAAAABAE" # Ruta de la imagen (opcional)
    amount: 1
  Gold:
    price: 500
    name: "&l&5EPIC{LINE}&r&0x{AMOUNT} {LINE} | kostet: {PRICE}€"
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngegg.com%2Fen%2Fpng-fnamm&psig=AOvVaw2vj7EnS_vdBuL_hnzty_BI&ust=1709039085727000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIji4O6IyYQDFQAAAAAdAAAAABAF" # Ruta de la imagen (opcional)
    amount: 1
  Kupfer:
    price: 750
    name: "&l&5EPIC{LINE}&r&0x{AMOUNT} {LINE} | kostet: {PRICE}€"
    image: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fstatic.wikia.nocookie.net%2Fcreate_mod%2Fimages%2F0%2F00%2FCopper_Ingot.png%2Frevision%2Flatest%2Fthumbnail%2Fwidth%2F360%2Fheight%2F450%3Fcb%3D20220715092204&tbnid=iYNuG1fUrPYduM&vet=10CAgQxiAoAWoXChMIiK-UjYnJhAMVAAAAAB0AAAAAEAk..i&imgrefurl=https%3A%2F%2Fcreate.fandom.com%2Fwiki%2FCopper_Ingot&docid=Nuh5qKELvsRRjM&w=360&h=360&itg=1&q=kupfer%20minecraft.png&ved=0CAgQxiAoAWoXChMIiK-UjYnJhAMVAAAAAB0AAAAAEAk" # Ruta de la imagen (opcional)
    amount: 1
  Diamond:
    price: 1250
    name: "&l&5EPIC{LINE}&r&0x{AMOUNT} {LINE} | kostet: {PRICE}€"
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vhv.rs%2Fviewpic%2FTRxbJwh_minecraft-diamonds-png-gold-ingot-minecraft-transparent-png%2F&psig=AOvVaw2ihQBR7ipX7XpzKbxzlILQ&ust=1709039221062000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLjPm6-JyYQDFQAAAAAdAAAAABAF" # Ruta de la imagen (opcional)
    amount: 1
  Netherite:
    price: 1750
    name: "&l&5EPIC{LINE}&r&0x{AMOUNT} {LINE} | Kostet: {PRICE}€"
    image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fminecraft.fandom.com%2Fwiki%2FNetherite_Ingot&psig=AOvVaw1MYUrB_OaJVC2TnBHlded1&ust=1709039296518000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPjbk9OJyYQDFQAAAAAdAAAAABAF" # Ruta de la imagen (opcional)
    amount: 1

# Form => Keyshop
Form:
  title: "&l&fKEYSHOP"
  content: "&eSelect the key of your preference:"
# Messages
Messages:
  error:
    no-config: "&cApparently there are no keys available..."
    no-money: "&cYou don't have enough money to make this purchase!"
  success:
    successful-purchase: "&aYou have purchased &bx{AMOUNT} {KEY}&a keys for only &b{PRICE}$"
